### ISSUE TITLE
Transform classes in attributes

### ISSUE THREAD

**Issue by belozer** [tadatuta/postcss-css-to-bem-css#3]
```css
[class*='block_mod'] {} → [class*='Block_mod'] {}
```

Для кейсов, когда нужно сделать стили для всех значений модификаторов.

```css
.block_mod_val {}
.block_mod_val2 {}
.block_mod_val3 {}
```

**Comment by tadatuta** [comment]
branch with falling test: https://github.com/tadatuta/postcss-css-to-bem-css/tree/issues/3
